# 示例配置 https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

# 连接服务端的地址。
serverAddr = "youdomain.com"
# 连接服务端的端口
serverPort = 9550
# 用户名，设置此参数后，代理名称会被修改为 {user}.{proxyName}，避免代理名称和其他用户冲突。
user = "PC"

# 客户端鉴权配置。
auth.method = "token"
auth.token = "qazWSX!@#"

# 客户端 AdminServer 配置。
webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "qazWSX!@#123"

# 客户端网络层配置。
transport.poolCount = 5

# 此处写要启动的 proxies 和 visitors 的 name
start = ["tcp", "blog"]

# 访问链接 youdomain:9553
[[proxies]]
name = "tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
# 设置0 则随机分配
remotePort = 9553


[[proxies]]
name = "blog"
type = "http"
localIP = "127.0.0.1"
localPort = 8080

# 访问链接 http://blog.youdomain.com:9551
subdomain = "blog"
# 访问链接 http://youdomain.com:9551
customDomains = ["youdomain.com"]

requestHeaders.set.power = "sakura"
responseHeaders.set.power = "sakura"

[[proxies]]
name = "RDP-TCP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
# 访问链接 youdomain.com:9554
remotePort = 9554

[[proxies]]
name = "pc-rdp-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
# 访问链接 youdomain.com:9570
remotePort = 9570

#  stcp
[[proxies]]
name = "pc-rdp-stcp"
type = "stcp"
localIP = "127.0.0.1"
localPort = 3389
secretKey  = "SSXXZZYYAABBWY90TM"

# 开启p2p 开启 xtcp
[[proxies]]
name = "pc-rdp-xtcp"
type = "xtcp"
localIP = "127.0.0.1"
localPort = 3389
secretKey  = "SSXXZZYYAABBWY80TM"

#  stcp 访问
[[visitors]]
name = "visit-rdp"
type = "stcp"
serverName = "pc-rdp-stcp"
secretKey  = "SSXXZZYYAABBWY90TM"
bindAddr  = "127.0.0.1"
bindPort  = 13390

# p2p 模式  xtcp 访问
[[visitors]]
name = "visit-pc-rdp"
type = "xtcp"
# 与主配置中的 name 和 sk 一致
serverName = "pc-rdp-xtcp"
secretKey  = "SSXXZZYYAABBWY80TM"
bindAddr  = "127.0.0.1"
bindPort  = 13389

